In [2]:
import numpy as np
import pandas as pd

## Create Series

In [12]:
num = np.random.randint(low=5, high=20, size=10)
num

array([17,  5, 19, 11,  6, 16, 15,  7, 12, 12])

In [17]:
df1 = pd.DataFrame({'Num' : num})
df1

   Num
0   17
1    5
2   19
3   11
4    6
5   16
6   15
7    7
8   12
9   12

In [18]:
df1.shape

(10, 1)

In [24]:
df1.index

RangeIndex(start=0, stop=10, step=1)

In [25]:
df1.columns

Index(['Num'], dtype='object')

## Perform Indexing

In [66]:
#First row
df1.iloc[1]

Num    5
Name: 1, dtype: int64

In [68]:
#Slicing row
df1.iloc[:5]

   Num
0   17
1    5
2   19
3   11
4    6

In [72]:
#Get specific value
df1.loc[4, 'Num']

np.int64(6)

## Filtering

In [73]:
df1[df1['Num'] > 15]

   Num
0   17
2   19
5   16

In [74]:
df1[df1['Num'] % 2 == 0]

   Num
4    6
5   16
8   12
9   12

## Statistical Operations

In [75]:
print(f"Mean: {df1['Num'].mean()}")
print(f"Maximum: {df1['Num'].max()}")
print(f"Minimum: {df1['Num'].min()}")
print(f"Median: {df1['Num'].median()}")

Mean: 12.0
Maximum: 19
Minimum: 5
Median: 12.0